### ISSUE TITLE
Error: Cannot find module 'nodepie'

### ISSUE THREAD

**Issue by Valiantiam** [larcher/hubot-rss-alerts#2]
`ERROR Unable to load /home/hubot/node_modules/hubot-rss-alerts/src/rss-alerts: Error: Cannot find module 'nodepie'`

I installed following the directions. Keep getting this error no matter what.

**Comment by larcher** [comment]
Thanks for the report, I'll take a look. I suspect I need to add `nodepie` as a dependency in `package.json`.  

As a workaround in the meantime, you could try installing nodepie manually with `npm install nodepie`
